# Configuración para Base de Datos H2 (La que no requiere instalación)
spring.datasource.url=jdbc:h2:mem:salon_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto permite ver las tablas en tu navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Esto crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true